<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="website">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="info" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="logo">
                                <xs:complexType>
                                    <xs:attribute name="path" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="movies" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="category" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="movie" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="isbn" minOccurs="1" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                              <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
                                                            </xs:restriction>
                                                          </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1" />
                                                    <xs:element name="poster" type="xs:string" minOccurs="1" maxOccurs="1" />
                                                    <xs:element name="score" type="xs:string" minOccurs="1" maxOccurs="1" />
                                                    <xs:element name="directors">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="director" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="actors">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="actor" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                                                                <xs:element name="actress" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="rating" type="xs:string" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="cat" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
